[package]
name = "host"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
model = { workspace = true }
store = { workspace = true }
docker = { workspace = true }
engine = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
