[package]
name = "store"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
model = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
keyring = { workspace = true }
dirs = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
